baseURL = "http://juan-fernandez.netlify.app"
languageCode = "en-us"
title = "Juan Fernandez Arias"
defaultcontentlanguage = "en"
theme = "hugo-coder"

# baseurl = "http://www.example.com"
# title = "johndoe"
# theme = "hugo-coder"
# languagecode = "en"
# defaultcontentlanguage = "en"

paginate = 20

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "jfdzar"

[params]
  author = "Juan Fernandez Arias"
  info = "Hardware Engineer"
  description = "Juan Fernandez Arias's personal website"
  keywords = "blog,hardware,personal"
  avatarurl = "images/juan.png"
  #gravatar = "jfdzar@gmail.com"

  favicon_32 = "/img/favicon-32x32.png"
  favicon_16 = "/img/favicon-16x16.png"

  footercontent = "Juan Fernandez Arias Personal Website"
  hideFooter = false
  hideCredits = false
  hideCopyright = false
  since = 2021

  enableTwemoji = true

  colorsheme = "auto"
  hidecolorschemetoggle = false

  customCSS = ["css/custom.css"]
  customSCSS = ["scss/coder.scss"]
  customJS = ["js/dark-mode.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/jfdzar/"
[[params.social]]
  name = "Twitter"
  icon = "fa fa-twitter fa-2x"
  weight = 3
  url = "https://twitter.com/jfdzar/"

# Menu links
[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "blog/"
[[menu.main]]
  name = "About"
  weight = 2
  url = "about/"