baseurl: http://juan-fernandez.netlify.app
languageCode: en-us
theme: hugo-theme-stack
paginate: 5
title: Juan Fernandez Arias

enableEmoji: true

# Change it to your Disqus shortname before using
disqusShortname: jfdzar

# Theme i18n support
# Available values: en, fr, id, ja, ko, pt-br, zh-cn
DefaultContentLanguage: en

permalinks:
    post: /p/:slug/
    page: /:slug/

params:
    mainSections:
        - post
    featuredImageField: image
    rssFullContent: true
    favicon:

    footer:
        since: 2020
        customText:

    dateFormat:
        published: Jan 02, 2006
        lastUpdated: Jan 02, 2006
        # lastUpdated: Jan 02, 2006 15:04 MST

    sidebar:
        emoji:
        subtitle: Hardware Engineer and Maker
        avatar:
            local: true
            src: img/juan-square-small.png

    article:
        math: false
        license:
            enabled: false
            default: Licensed under CC BY-NC-SA 4.0

    comments:
        enabled: false
        provider: disqus
        utterances:
            repo:
            issueTerm: pathname
            label:
            theme: preferred-color-scheme

    widgets:
        enabled:
            - search
            - archives
            - tag-cloud

        archives:
            limit: 5

        tagCloud:
            limit: 10

    opengraph:
        twitter:
            # Your Twitter username
            site:

            # Available values: summary, summary_large_image
            card: summary_large_image

    defaultImage:
        opengraph:
            enabled: false
            local: false
            src:

    colorScheme:
        # Display toggle
        toggle: true

        # Available values: auto, light, dark
        default: auto

    imageProcessing:
        cover:
            enabled: true
        content:
            enabled: true

menu:
    main:
        - identifier: home
          name: Home
          url: /
          weight: -100
          pre: home

        - identifier: about
          name: About
          url: about
          weight: -90
          pre: user

        - identifier: post
          name: Blog
          url: post
          weight: -80
          pre: archives
       

        - identifier: archives
          name: Archives
          url: archives
          weight: -70
          pre: archives

        - identifier: contact
          name: Contact
          url: contact
          weight: -60
          pre: user 

        - identifier: search
          name: Search
          url: search
          weight: -50
          pre: search 




related:
    includeNewer: true
    threshold: 60
    toLower: false
    indices:
        - name: tags
          weight: 100

        - name: categories
          weight: 200

markup:
    highlight:
        noClasses: false
